# --- Serving options --- #

# url is the full website URL
# baseurl is the website's URL without the hostname

# If you are building a simple GitHub user page (username.github.io) then use these settings:
#url: "http://username.github.io"
#baseurl: ""

# If you are building a GitHub project page then use these settings:
url: "https://atuladhar-aman.github.io/blog/"
baseurl: "/blog"

# Of course don't forget to change the username and projectname to YOUR username and project

# Name of website
title: Aman Tuladhar

# Short description of your site
description: Developer / Programmer

# --- Navigation bar options --- #

# Image to show in the navigation bar - image must be a square (width = height)
# Remove this parameter if you don't want an image in the navbar
avatar: "/img/avatar-icon.png"

# List of links in the navigation bar
navbar-links:
  Blog: ""
  About me: "https://atuladhar-aman.github.io/"

# --- Footer options --- #

# Change all these values or delete the ones you don't want.
# Important: you must keep the "name" parameter, everything else you can remove
author:
  name: Aman Tuladhar
  email: "atuladhar.aman@gmail.com"
  facebook: freakinbuoy07
  github: atuladhar-aman
  twitter: atuladhar_aman
  linkedin: "linkedin"
  stackoverflow: "users/5065092/aman-tuladhar"
 
# Select which links to show in the footer
footer-links-active:
  rss: false
  facebook: true
  email: true
  twitter: true
  github: true
  linkedin: false
  stackoverflow: true

# How to display the link to the website in the footer
# Remove this if you don't want a link in the footer
url-pretty: "https://atuladhar-aman.github.io/blog/"

# --- Misc --- #

# Fill in your Disqus shortname (NOT the userid) if you want to support Disqus comments
disqus: "devloperblog"

# --- Don't need to touch anything below here (but you can if you want) --- #

# Output options (more information on Jekyll's site)
timezone: "America/Vancouver"
markdown: kramdown
highlighter: rouge
permalink: /:year-:month-:day-:title/
paginate: 10


# Fill in your Google Analytics ID to track your website using GA
google_analytics: "UA-85087934-1"

# Default YAML values (more information on Jekyll's site)
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true  # add comments to all blog posts 
      show-share: true # add sharing buttons to all blog posts
  -
    scope:
      path: "" # all files
    values:
      layout: "page"

# Exclude these files from production site
exclude:
  - CNAME
  - LICENSE
  - README.md
  - Gemfile
  - Gemfile.lock
  - Dockerfile
  - Dockerfile.prod
  - docker-compose.yml

gems:
  - jekyll-sitemap
  - jekyll-paginate