version: "2"
services:
  github-blog:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - 80:4000
    entrypoint: bundle exec jekyll serve -H 0.0.0.0